exports.questions = [
    {"indx":1, 
    "description":"Why did the dog feel the need for a master? "},
    {"indx":2, 
    "description":"Who did he first choose as his master? Why did he leave that master? "},
    {"indx":3, 
    "description":"Who did he choose next? "},
    {"indx":4, 
    "description": "Why did he serve the Lion for a long time?"},
    {"indx":5, 
    "description": " Who did he finally choose as his master and why?"},
    {"indx":6, 
    "description": " Why did the dog feel he needed a master?"},
    {"indx":7, 
    "description": " Why did the dog serve the lion for a long time?"},
    {"indx":8, 
    "description": " Why did the dog leave his first master ?"},
    {"indx":9, 
    "description": " Who was the Bear afraid of?"},
    {"indx":10, 
    "description": " What does the writer say about the friendship between man and dog?"},
    {"indx":11, 
    "description": " That dog thought to became servant of? a. Humans b. Lion c. Bear d. Strongest."},
    {"indx":12, 
    "description": "  Why the dog thought to serve himself to the strongest creature? a. He was afraid of other animals b. He was tired of looking for the food everyday c. Both d. None."},
    {"indx":13, 
    "description": "  With whom dog first met? a. Bear b. Wolf c. Human d. Lion."},
    {"indx":14, 
    "description": "  For the hunt of which animal bear went with the dog in the forest? a. Hen b. Cows c. Jackal d. Deer."},
    {"indx":15, 
    "description": "  With which animal the bear got frightened? a. Tiger b. Lion c. Wolf d. Deer."},
    
]
