exports.questions = [
    {"indx":1, 
    "description":"What did Patrick think his cat was playing with? What was it really?"},
    {"indx":2, 
    "description":"Why did the little man grant Patrick a wish?"},
    {"indx":3, 
    "description":"What was Patrick’s wish?"},
    {"indx":4, 
    "description": "In what subjects did the little man need help, to do Patrick’s homework?"},
    {"indx":5, 
    "description": " How did Patrick help him?"},
    {"indx":6, 
    "description": " Who do you think did Patrick’s homework — the little man, or Patrick himself?"},
    {"indx":7, 
    "description": " This story has a lot of rhyming words, as a poem does. Can you write out some parts of it like a poem, so that the rhymes come at the end of separate lines? For example: patrick never did homework. “Too boring,” he said. He played baseball and hockey and Nintendo instead."},
    {"indx":8, 
    "description": " Why did Patrick save the elf from the cat?"},
    {"indx":9, 
    "description": " How did the elf react when he heard the wish of Patrick?"},
    {"indx":10, 
    "description": " How did the elf do Maths and History?"},
    {"indx":11, 
    "description": " What were the reactions of others over Patrick’s result?"},
    {"indx":12, 
    "description": " What did Patrick think about homework before meeting the elf?"},
    {"indx":13, 
    "description": "  What game does Patrick do not play? a. Hockey b. Basketball c. Nitendo d. All"},
    {"indx":14, 
    "description": " What Patrick hate? a. Basketball b. Homework c. Nitendo d. Hockey"},
    {"indx":15, 
    "description": " The doll with whom the cat was playing was actually: a. Toy b. Elf c. Doll d. Cat"},
    {"indx":16, 
    "description": " What the elf yelled? a. Help me! b. Go away! c. Who are you? d. Save me!?"},
    {"indx":17, 
    "description": " The shirt of the elf was made up of: a. Cotton b. Wool c. Nylon d. Silk"},


]
