
exports.questions = [
    {"indx":1, 
    "description":"Describe a recent quarrel that you have had with your brother, sister or friend. How did it start? What did you quarrel about? How did it end?"},
    {"indx":2, 
    "description":"With your partner try to guess the meaning of the underlined phrases. (i) And somehow we fell out. (ii) The afternoon turned black.    "},
    {"indx":3, 
    "description":"Why did the brother patted on his back?    "},
    {"indx":4, 
    "description": " Give the meaning of 'thumped'."},
    {"indx":5, 
    "description": " What kind of relationship did the siblings shared "},
    {"indx":6, 
    "description": "  What was the intention of the brother?"},
    {"indx":7, 
    "description": " Why does oi 'turn black'?"},
    {"indx":8, 
    "description": " The author of the above poem is (a) L.M. Halli (b) Harry Behn (c) Eleanor Farjeon (d) Y-Yeh-Shure."},
    {"indx":9, 
    "description": " It seems that the brothers quarrelled on (a) a petty matter (b) some very important matter (c) money matter (d) property.    "},
    {"indx":10, 
    "description": " : Both the brothers felt that the other was (a) right (b) wrong (c) honest (d) dishonest."},
    {"indx":11, 
    "description": " The phrase ‘fell out’ means that the brothers (a) fell on the ground (b) fell from the roof (c) fell on the road (d) became unfriendly    "},
    {"indx":12, 
    "description": " The afternoon turned black because the two of them (a) were angry (b) were disappointed (c) had lost the way (d) had quarrelled.    "},
   
]
