exports.questions = [
    {"indx":1, 
    "description":"Why did the author feel isolated in his new school?"},
    {"indx":2, 
    "description":"Why did the mother run back into the house for the second time?"},
    {"indx":3, 
    "description":"How did the author feel when he went to his new school after the fire accident?"},
    {"indx":4, 
    "description": "Describe the author’s love for his cat. Do you also have the same feelings for your pet?"},
    {"indx":5, 
    "description": " Write a brief character sketch of the author. What impresses you the most?"},
    {"indx":6, 
    "description": " What is the story ‘A House is not a Home’ about? A) defines a home B) defines a house C) None D) differentiates between a house and a home."},
    {"indx":7, 
    "description": " What is a house? A) a building which people use to live B) a place C) a property D) None "},
    {"indx":8, 
    "description": " What is a home? A) where people live together and share a bond of love and care B) a house only C) a property D) None."},
    {"indx":9, 
    "description": " Why did the narrator feel strange in high school? A) because he was fresh B) all his friends went to other places C) because he was all alone D) All."},
    {"indx":10, 
    "description": " What was Zan doing when fire broke out? A) was playing B) was in neighbourer's house C) was sleeping D) was doing his homework."},
    {"indx":11, 
    "description": " Do you agree with what the poet says? Talk to your partner and complete these sentences.(i) A house is made of.......... (ii) It has............. (iii) A home is made by ........ (iv) It has ....."},

]
