
exports.questions = [
    {"indx":1, 
    "description":"Why did Taro run in the direction of the stream?"},
    {"indx":2, 
    "description":"How did Taro’s father show his happiness after drinking saké? "},
    {"indx":3, 
    "description":"Why did the waterfall give Taro saké and others water?  "},
    {"indx":4, 
    "description": " Why did the villagers want to drown Taro?"},
    {"indx":5, 
    "description": " Why did the Emperor reward Taro? "},
    {"indx":6, 
    "description": "  How much did he love his parents?"},
    {"indx":7, 
    "description": " What happened in one cold evening? What did Taro’s father wish to have?"},
    {"indx":8, 
    "description": " To quench his thirst when he drank water what surprising thing did Taro find?"},
    {"indx":9, 
    "description": " Next morning when did Taro visit the waterfall? What did he carry then? Why?"},
    {"indx":10, 
    "description": " When Taro tasted the water back what did he discover? How was his experience different from Taro?"},
    {"indx":11, 
    "description": " What was Taro’s profession a. Wood picker b. Wood cutter c. Shepherd d. Blacksmith."},
    {"indx":12, 
    "description": "  With whom Taro lived? a. Father b. Mother c. Both d. None."},
    {"indx":13, 
    "description": " Why Taro went to the wood early in the morning? a. To cut more woods b. To buy sake c. to prevent sun stroke d. None.    "},
    {"indx":14, 
    "description": "  Why Taro stopped cutting wood ? a. He heard the sound of rushing water b. He fell from the tree c. He saw a golden axe d. He got sick.    "},
    {"indx":15, 
    "description": " How the water of water-fall felt to Taro? a. Cold water b. Sweet water c. Sake d. Lemonade.    "},
   
]
